#!/usr/bin/env python3
'''
@Autor: Ana Maria Sandoval Jimenez
'''

from pprint import pprint
import sys
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab
import seaborn as sns; sns.set()
plt.style.use('fivethirtyeight')
pylab.rcParams['figure.figsize'] = (10.0,8.0)

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
###################import pandas_profiling
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.cross_validation import cross_val_score

from sklearn.preprocessing import PolynomialFeatures

from sklearn.pipeline import make_pipeline
# load preprocesed train test files
try:
    train = pd.read_csv(sys.argv[1])
    test = pd.read_csv(sys.argv[2])
except IndexError:
    print("usage: linear-reg TRAIN-FILE TEST-FILE")
    sys.exit(1)
                    
#Training a Linear Regression Model
print('Train shape: ', train.shape)
print('Test  shape: ', test.shape)
print(" ")
print('Train columns: ')
pprint(train.columns)
print('Train columns: ')
pprint(test.columns)

y = train['mortality_rate']
X = train.drop(['mortality_rate'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 101)

lm = LinearRegression()
lm.fit(X_train,y_train)

#Model evaluation
print(lm.intercept_)
coeff_train = pd.DataFrame(lm.coef_,X_train.columns, columns=['Coefficient'])
print(coeff_train)

# Predictions
predictions = lm.predict(X_test)

# Metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

# Model validation via cross-validation
print('Cross validation Score:')
score = cross_val_score(lm, X, y, cv=5)
print(score)
print('CV mean: ', score.mean())

# Selecting the Best Model
plt.scatter(X.ravel(), y, color='black')
axis = plt.axis()
for degree in [1, 3, 5]:
        y_test = PolynomialRegression(degree).fit(X, y).predict(X_test)
           plt.plot(X_test.ravel(), y_test, label='degree={0}'.format(degree))
            plt.xlim(-0.1, 1.0)
            plt.ylim(-2, 12)
            plt.legend(loc='best');

